### ISSUE TITLE
Check if QDA is feasible tool for manual tagging of NEs

### ISSUE THREAD

**Issue by mbojan** [poi-hnr/data-letters#1]
- Can we use QDA for manual tagging of patterns?
- Can we export the model output to QDA format? Check QDA file format.

**Comment by mbojan** [comment]
@dvasques83 @agatabloch So I did a little bit of testing of the QDA. More precisely, it is "QDA Miner Lite" (free) from here https://provalisresearch.com/products/qualitative-data-analysis-software/freeware/ The results are promising, but there is one key feature missing, namely:

It does not seem possible to export `start` and `end` locations of the tagged text, only the text itself. See example output below. @dvasques83 is it a crucial problem for us?

Above problem aside, the workflow could be along the following lines:

1. Generate the ~4000 plain files to be annotated.
2. Import all 4000 into a single QDA project. I don't think it should be a problem as the files will be small. I just created a project with 1000 files for testing.
3. Create the dictionary of codes (i.e. labels)
4. Do the annotation
5. Export the codes (called "Code retrieval" in QDA). This generates a CSV file like this:

```
,Category,Code,,Case,Text,Coder,Date,Words,% Words,Comment,WORDS
,code_group1,label1,," Case #1",radiowej,Admin,11/7/2017,1,12.5%,,TEXT
,code_group2,label2,," Case #1",obiektów,Admin,11/7/2017,1,12.5%,,TEXT
,code_group1,label1,," Case #1",FRID,Admin,11/7/2017,1,12.5%,,TEXT
,code_group1,label1,," Case #2",badawczego,Admin,11/7/2017,1,10.0%,,TEXT
,code_group2,label2,," Case #2",Identyfikacji,Admin,11/7/2017,1,10.0%,,TEXT
```

So there is a row for every piece of tagged text, assigned Codes (labels), the text itself in (`Text`), but no information about `start` and `end`. Unfortunately there is also no option for importing pre-annotated text, so the coders will not be able to see the tagging pre-generated by the model.

I looked for alternative tools. It seems that MAXQDA (http://www.maxqda.com/licenses/order-information) is able to export start/end. There is no free version unfortunately. Student version costs about $50.

**Comment by mbojan** [comment]
I should add that the QDA file format is binary, so no easy hacking there.

**Comment by dvasques83** [comment]
The 'start' and 'end' positions are crucial to train the model, unfortunately. Perhaps it is worth getting MAXQDA's 14 days trial, after we have the data ready to manipulate.

The output "Code retrieval" in QDA seems fine to handle, if we decide to go this way. 'start' and 'end' positions should be added manually though.

There are two new files in the repo: a .txt (train_poi_data.txt) with the documents all together and a .zip file (train_poi_data.zip) with 4,230 individual files. Those were generated randomly, but I am using a fixed seed if we need to generate it over and over.

**Comment by mbojan** [comment]
Another option: GATE. See screens here https://gate.ac.uk/sale/tao/splitch3.html#x6-350003.4 I have not tested it yet.

**Comment by mbojan** [comment]
We met with @agatabloch and check out MAXQDA. It seems it will work!  

Even though none of the built-in export options gives us what we need (coded text fragments together with the start and end positions), it is possible to hack the "MAXQDA exchange files" and extract them from there.

Stay tuned.

**Comment by mbojan** [comment]
The good workflow seems to be:

1. Import full texts as separate text files into a single MAXQDA project
2. Do the coding/tagging.
3. Export the project as MAXQDA Exchange File (`.mex`).
4. Use https://github.com/mbojan/maxqdar to convert it to a CSV, or something else for that matter, of the form (R data frame preview):
```
    ## # A tibble: 402 x 9
    ##       ID TextID WordID Preview          start   end file_n~ tag   preview~
    ##    <int>  <int>  <int> <chr>            <int> <int> <chr>   <chr>    <int>
    ##  1     1      2      8 AVISO               30    35 0_229   TYPE         5
    ##  2     2      2      7 "secret\u00e1ri~    39    61 0_229   ROLE        21
    ##  3     3      2      5 "Diogo de Mendo~    61    90 0_229   PERS~       28
    ##  4     4      2      5 Aires de Saldan~   123   155 0_229   PERS~       32
    ##  5     5      2      5 "Jos\u00e9 de S~   254   274 0_229   PERS~       20
    ##  6     6      2      5 Lucas Ribeiro d~   392   417 0_229   PERS~       24
    ##  7     7      2      7 "capit\u00e3o-m~   366   392 0_229   ROLE        25
    ##  8     8      2      7 governador do R~    93   121 0_229   ROLE        28
    ##  9     9      2      7 soldados           311   319 0_229   ROLE         8
    ## 10    10      2      4 1722, Maio, 28       7    21 0_229   DATE        14
    ## # ... with 392 more rows
```


There is one caveat: MEX files contain raw data in binary format which I so far was not able to hack. I was able to extract only a Preview, which is at most first 63 characters of the coded string. 63 is not a lot and the portion of texts @agatabloch was coding (b)reaches that limit 17 times. However, only 1 of those something else than MISC. To be on the safe side, data from the table above (filename, start, end) could be used to re-extract coded fragments.

What do you think @dvasques83 ?

**Comment by dvasques83** [comment]
It seems that this will work fine. Was that 17 times out of how many? If it is was out of 145, we should be fine. 'Losing' 10 to 15% of the training data is not a bid deal.

**Comment by mbojan** [comment]
Maxqda turned out pretty feasible ;)
